version: '3'
services:
    app:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-twitter-clone/php8.0
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres_srv
            - redis_srv
        restart: always

    postgres_srv:
      image: 'postgres:13'
        ports:
          - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
          PGPASSWORD: '${DB_PASSWORD:-secret}'
          POSTGRES_DB: '${DB_DATABASE}'
          POSTGRES_USER: '${DB_USERNAME}'
          POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
          - 'sailpgsql:/var/lib/postgresql/data'
        networks:
          - sail
        healthcheck:
          test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
          retries: 3
          timeout: 5s

    redis_srv:
        image: redis:6.2-alpine
        ports:
          - '${REDIS_PORT:-6379}:6379'
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
          - 'sailredis:/data'
        networks:
          - sail

networks:
    sail:
        driver: bridge

volumes:
    sailpgsql:
        driver: local
    sailredis:
        driver: local
